module.exports = {
    enrollment: '<div class="popup_index"> <p><strong> 当前选课人数 </strong>本课程当前正在选课人数（同一账号能且仅能计一次数），即：</p> <img class="popup_images" ng-src="{{:: staticDir}}/index_direction/current-enroll.png"> </div>',
    register: '<div class="popup_index"> <p><strong> 累计报课人次 </strong>本课程累计注册人次（同一账号可计入多次，举例：小王注册了课程A，然后跟不上退了课，接着在好友的鼓励下再次注册，则算作2次注册）。</p> </div>',
    unenrollment: '<div class="popup_index"> <p><strong> 累计退课人次 </strong>本课程累计退课人次（同一账号可计入多次，举例：小王注册了课程A，然后跟不上退了课，接着在好友的鼓励下再次注册，但仍然跟不上再次退课，则算作2次退课）。</p> </div>',
    habit: '<div class="popup_index"> <p> <strong> 学习活跃时间热力图 </strong>直观地展示用户最近2周的学习习惯（喜欢在周几学？喜欢在哪个时间段学？），格子越深 表示当日该小时的在线学习人数越多。 </p> </div>',
    attention: '<div class="popup_index"> <p>本课程当前正在选课的人数。</p> </div>',
    schedule: '	<div class="popup_index"> <p> <strong> 学习人数占比 </strong> 学习（包括：观看视频，讨论发言，做题等）本章的用户占选课总人数的比例，即： <img class="popup_images" ng-src="{{:: staticDir}}/index_direction/study-percent.png"> </p> </div>',
    discuss: '<div class="popup_index"> <p><strong> 讨论区 · 昨日新增发帖数 </strong> 课程讨论区中无昨日00:00至24:00的发帖数（不包括回复数）</p> </div>',
    score: '	<div class="popup_index"> <p><strong> 答题用户 · 平均得分分布 </strong> 直观地展示答题用户（无答题记录的用户不作统计）的得分分布（比如：课程进行到第三章，共投放平时分30分，若用户得分为15分，则其得分率为50%），横坐标 表示得分率；纵坐标 表示该得分率下的用户数。</p> </div>',
    assistant: '<div class="popup_index"> <p><strong> 助教回帖数 </strong>每个论坛管理员（可在教师工具中配置）在讨论区中的回帖总数（以及昨日回帖数）。其中 论坛管理员 标记为红色；论坛版主 标记为蓝色；论坛社区助教 标记为绿色。</p> </div>',
    health: '<div class="popup_index"> <p> <strong> 课程健康度 </strong>从学习者规模和学习社区运营两个方面的5个指标（包括：学习者7日活跃率、学习者总规模；讨论区发帖回复率、讨论区人均互动与次数、讨论区参与规模），概览式地展示课程运营整体情况。 </p> </div>',
    newinactive: '<div class="popup_index"><p>在过去7天内没有学习的用户。</p></div>',
    revival: '<div class="popup_index"><p>本周期之前为沉睡用户，在本周期内又再度开始学习的用户。</p></div>',
    active: '<div class="popup_index"> <p> <strong> 学习者7日活跃率 </strong> 7日活跃用户占本课程总选课人数的比例。 <img class="popup_images" ng-src="{{:: staticDir}}/index_direction/day7.png"> 活跃用户选课学生在过去的7天中有学习行为（包括：观看视频，讨论发言，做题等）的用户。沉睡用户 若选课学生在过去的7天中有学习行为的用户（沉睡用户再次学习，则为复活，再次标记为活跃用户）。 </p> </div>',
    studyScale: '<div class="popup_index"> <p> <strong> 学习者总规模 </strong> 即：当前选课人数本课程当前正在选课人数（同一账号能且仅能计一次数），即： <img class="popup_images" ng-src="{{:: staticDir}}/index_direction/current-enroll.png"> </p> </div>',
    reply: '<div class="popup_index"> <p> <strong> 讨论区发帖回复率 </strong>课程讨论区中有回复的帖子数占总发帖数的比例，即： <img class="popup_images" ng-src="{{:: staticDir}}/index_direction/has-reply-percent.png"> </p> </div>',
    interaction: '<div class="popup_index"> <p> <strong> 讨论区人均互动与次数 </strong>课程讨论区中人均发言次数（包括：发帖数和回帖数），即： <img class="popup_images" ng-src="{{:: staticDir}}/index_direction/avg-discuss-count.png"> </p> </div>',
    discussionJoin: '<div class="popup_index"> <p> <strong> 讨论区参与规模 </strong>即： 讨论区参与人数 选课用户中有发言记录的人数（包括：发帖数和回帖数）。 </p> </div>',
    userInfo: '<ul class="user_info_popup"> <li><a ng-href="{{:: outline}}" target="_blank">查看课程</a></li> <li><a ng-href="{{:: settings}}" target="_blank">设置课程</a></li> <li><a href="/logout">退出</a></li> </ul>',
    regional: '<div class="popup_index"> <p><strong> 选课地域分布图 </strong>直观地展示本课程的选课人数地域分布，圈的面积 表示不同省市的选课人数（当前用户所在省市基于最后一次学习的网络接入地点判断）。</p> </div>',
    tsinghua: '	<div class="popup_index"> <p><strong> 清华 · 选修人数 </strong>选课学生中绑定清华大学账号的人数（更多学校账号绑定，请联系 <a href="mailTo:support@xuetangx.com">support@xuetangx.com）</a>。</p> </div>',
    inactive: '<div class="popup_index"> <p><strong> 活跃用户占比 </strong>活跃用户占本课程总选课人数的比例。</p> <img class="popup_images" ng-src="{{:: staticDir}}/index_direction/day7.png"> </div>',
    nextWeekActive: '<div class="popup_index"> <p><strong> 未来一周活跃率 </strong>预测下周的活跃（访问过课件）人数占总选课人数的比例</p> </div>',
    lastWeekError: '<div class="popup_index"> <p><strong> 误差 </strong>与真实流失率相比，上周的预测流失误差值</p> </div>',
    nextWeekRunOffRate: '<div class="popup_index"><p><strong> 未来一周流失率 </strong>预测下周流失人数占总选课人数的比例</p> </div>',
    certificateRate: '<div class="popup_index"> <p><strong> 获得证书占比 </strong>根据学习者历史学习行为和课程的历史结课情况，预测当前可获得本课程证书的人数占总报课人数的比例。预测算法由清华大学技术团队提供。</p> </div>',
    download_blackboard_1: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每个报课学生，及其个人信息</p><p><strong>包含以下字段：</strong></p><p>用户昵称、学堂号、真实姓名、学校名称、学号、邮箱。</p><p>更新于{{lesson.enrollment_export.updatetime}}</p></div>',
    download_blackboard_2: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每日各时段的学习人数。</p><p>更新于{{lesson.learn_active_export.updatetime}}</p></div>',
    download_blackboard_3: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每日课程的学习活跃情况。</p><p><strong>包含以下字段：</strong></p><p>每日活跃用户人数（＝在过去7日内有学习行为的用户）、每日新增复活人数（＝之前为沉睡用户，当天突然来学习的用户）、每日新增沉睡用户（＝在过去7日内有学习行为的用户）。</p><p>更新于{{lesson.course_active_export.updatetime}}</p></div>',
    download_blackboard_4: '<div class="popup_index"><p><strong>每张表格：</strong></p><p>每个已发布章节的学习进度。</p><p><strong>每行数据：</strong></p><p>每个学生的学习情况。</p><p><strong>包含以下字段：</strong></p><p>每个视频的学习比例、每个视频的复习比例、每道题目的对错、每道题目的答案。</p><p>更新于{{lesson.study_progress.updatetime}}</p></div>',
    download_blackboard_5: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每日讨论区活跃情况。</p><p><strong>包含以下字段：</strong></p><p>累计发帖数、每日新增发帖数、累计回帖数、每日新增回帖数、累计零回复帖子数、每日新增零回复帖子数。</p><p>更新于{{lesson.comment_active_export.updatetime}}</p></div>',
    download_blackboard_6: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每个分数的得分人数。</p><p>更新于{{lesson.grade_distribution_export.updatetime}}</p></div>',
    download_blackboard_7: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每个助教的回帖量。</p><p>更新于{{lesson.ta_activity_export.updatetime}}</p></div>',
    download_study_1: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每个学生每次的选课记录。</p><p><strong>包含以下字段：</strong></p><p>用户基本信息、每次报课日期时间、报课前浏览课程详情页次数、报课的访问来源。</p><p>更新于{{lesson.about_enroll.updatetime}}</p></div>',
    download_study_2: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每个学生每次的退课记录。</p><p><strong>包含以下字段：</strong></p><p>用户基本信息、每次退课日期时间。</p><p>更新于{{lesson.unenroll_info.updatetime}}</p></div>',
    download_study_3: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每个学生每次访问课程学习模块的记录。</p><p><strong>包含以下字段：</strong></p><p>用户基本信息、每次访问课程学习模块日期时间、访问来源。</p><p>更新于{{lesson.learn_info.updatetime}}</p></div>',
    download_study_count: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每个学生每次访问课程学习模块的次数。</p><p><strong>包含以下字段：</strong></p><p>用户基本信息、访问课程学习模块次数、访问来源。</p><p>更新于{{lesson.learn_cnt_info.updatetime}}</p></div>',
    download_study_4: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每个学生每次学习每个视频的记录。</p><p><strong>包含以下字段：</strong></p><p>用户基本信息、视频基本信息、开始观看日期时间、借宿观看日期时间、开始观看视频时间轴位置、结束观看视频时间轴位置。</p><p>更新于{{lesson.video_study_export.updatetime}}</p></div>',
    download_study_5: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每个学生每次学习每份教材的记录。</p><p><strong>包含以下字段：</strong></p><p>用户基本信息、教材基本信息、学习时间日期。</p><p>更新于{{lesson.pdf_view.updatetime}}</p></div>',
    download_study_6: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每个学生每次浏览/编辑/添加每个wiki词条的记录。</p><p><strong>包含以下字段：</strong></p><p>用户基本信息、wiki词条的基本信息、参与类型（浏览/编辑/添加）、参与日期时间。</p><p>更新于{{lesson.itmes[0].updatetime}}</p></div>',
    download_study_7: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每个学生每次访问课程中站外资源链接的记录。</p><p><strong>包含以下字段：</strong></p><p>用户基本信息、站外资源链接、访问日期时间。</p><p>更新于{{lesson.itmes[0].updatetime}}</p></div>',
    download_study_8: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每个学生每次访问课程中除课件、Wiki、学习进度页外其他页面的记录。</p><p><strong>包含以下字段：</strong></p><p>用户基本信息、页面信息、访问日期时间。</p><p>更新于{{lesson.html_view.updatetime}}</p></div>',
    download_study_9: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每个学生每题的得分记录。</p><p>更新于{{lesson.problem_info.updatetime}}</p></div>',
    download_study_10: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每个学生每题每次提交的记录。</p><p><strong>包含以下字段：</strong></p><p>用户基本信息、题目信息、提交答案、提交时间。</p><p>更新于{{lesson.sort_info.updatetime}}</p></div>',
    download_study_11: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每个学生每次访问课程讨论区的记录。</p><p><strong>包含以下字段：</strong></p><p>用户基本信息、每次访问课程讨论区的日期时间、访问来源。</p><p>更新于{{lesson.items[0].updatetime}}</p></div>',
    download_study_12: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每个学生每次发帖或回帖帖子的记录。</p><p><strong>包含以下字段：</strong></p><p>用户基本信息、帖子详细信息、参与日期时间。</p><p>更新于{{lesson.comments_info.updatetime}}</p></div>',
    download_study_13: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每个学生每次访问单个帖子的记录。</p><p><strong>包含以下字段：</strong></p><p>用户基本信息、帖子基本信息、访问日期时间。</p><p>更新于{{lesson.itmes[0].updatetime}}</p></div>',
    download_score_1: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>每个学员的当前总得分。</p><p>更新于{{lesson.grade.updatetime}}</p></div>',
    download_score_2: '<div class="popup_index"><p><strong>每行数据：</strong></p><p>合格学员的个人信息。</p><p>更新于{{test.itmes[0].updatetime}}</p></div>',
    download_lessonPersonal1: '',
    download_lessonPersonal2: '',
    interactMode_discuss: '<div class="popup_index"><p>整体发言趋势是怎样的？哪些同学比较活跃？谁和谁之间互动比较多？谁是整个讨论区的关键人物？本模块将和你一起透视讨论区中的互动秘密。</p></div>',
    interactMode_totalSpeakCount: '<div class="popup_index"><p>截至昨日24:00，讨论区中累计的总帖子数。</p></div>',
    interactMode_totalReplyCount: '<div class="popup_index"><p>截至昨日24:00，讨论区中累计帖子的总回复数。</p></div>',
    interactMode_zeroReplyCount: '<div class="popup_index"><p>截至昨天24:00，讨论区中没有被评论过的帖子数</p></div>',
    interactMode_replyTop5: '<div class="popup_index"><p>截至昨天24:00，在讨论区发表评论最多的前五名学生。</p></div>',
    interactMode_speakTop5: '<div class="popup_index"><p>截至昨天24:00，在讨论区发帖最多的前五名学生。</p></div>',
    difficulty_title: '<div class="popup_index"><p><strong>学生不容易理解的点在哪里？容易犯错的地方在哪里？</strong></p><p>结合教学视频的复看程度和习题的答题错误情况，综合分析定位出当前章节的难点位置，本模块将是您教学的辅助参考。</p></div>',
    difficulty_totalTime: '<div class="popup_index"><p>结合教学视频的复看程度和习题的答题错误情况，综合定位本章难点的时长总和。</p></div>',
    difficulty_reSeeTime: '<div class="popup_index"><p>本章节学生视频复看总时长（比如：一个学生针对一段2分钟的视频复看了5遍，则复看总时长为19分钟）。</p></div>',
    difficulty_errorCount: '<div class="popup_index"><p>通过文本分析将习题对应至相应讲授视频，并计算这些习题累计答错次数。</p></div>',
    difficulty_keyword: '<div class="popup_index"><p><strong>纵观本课程，学生都在哪些知识点上栽了坑？哪些坑之间会有连锁反应？</strong></p><p>本模块将和你一起从学生学习行为中发现关联的学习瓶颈。</p></div>'
}
